services:
  papper-history-service-mongo:
    image: mongo:7.0.9-rc1
    container_name: papper-history-service-mongo
    restart: unless-stopped
    volumes:
      - papper-history-service-mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${HISTORY_SERVICE_MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${HISTORY_SERVICE_MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${HISTORY_SERVICE_MONGO_DB_PASSWORD}
    ports:
      - 8410:27017
    networks:
      - papper-history-service-network
  papper-history-service:
    build: history_service
    container_name: papper-history-service
    restart: unless-stopped
    volumes:
      - ./history_service:/usr/src/history_service
    env_file:
      - ./history_service/.env
    ports:
      - 8400:8000
    depends_on:
      - papper-history-service-mongo
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/history_service/uvicorn_logging.conf"
    networks:
      - papper-history-service-network
      - papper-backend

volumes:
  papper-history-service-mongo-volume:

networks:
  papper-history-service-network:
    name: papper-history-service-network
  papper-backend:
    name: papper-backend
    external: true
